name: Brush
on:
  workflow_dispatch:
    inputs:
        site:
          description: site
          required: true
          default: 'nyt'
          type: string
  workflow_call:
    inputs:
        site:
          description: site
          required: true
          default: 'nyt'
          type: string
jobs:
  brush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10.19' #cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Cache playwright install
      id: cache-playwright-install
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache/ms-playwright
        key: ${{ runner.os }}-playwright
    - name: Install playwright
      if: true #steps.cache-playwright-install.outputs.cache-hit != 'true'
      run: playwright install --with-deps
    - name: Restore nltk_data from cache
      id: restore-nltk-cache
      uses: actions/cache@v4
      with:
        path: ~/nltk_data
        key: nltk_data
    - name: Install TextBlob corpora
      run: mkdir -p ~/nltk_data && NLTK_DATA=~/nltk_data python -m textblob.download_corpora lite
      if: steps.restore-nltk-cache.outputs.cache-hit != 'true'
    - name: Run env check
      run: python tools/test_env.py '${{ inputs.site }}'
      env:
        S3A: ${{ secrets.S3A }}
        WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}

    # Source - https://stackoverflow.com/a
    # Posted by aborilov, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-01-15, License - CC BY-SA 4.0
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Run script
      run: python simple_scrape.py '${{ inputs.site }}' --branch '${{ steps.extract_branch.outputs.branch }}'
      env:
        S3A: ${{ secrets.S3A }}
        WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
        NLTK_DATA: nltk_data
