name: Report scheduler
on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * *'
jobs:
  report:
    uses: wordnik/nyt-first-said/.github/workflows/report.yml@batch-3
    with:
      daysBackToGo: 1
