name: Report
on:
  workflow_dispatch:
    inputs:
        daysBackToGo:
          description: Days back to go
          required: false
          default: 1
          type: number
  workflow_call:
    inputs:
        daysBackToGo:
          description: Days back to go
          required: false
          default: 1
          type: number
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - uses: actions/setup-node@v6
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'js/tools/package-lock.json'

    # Source - https://stackoverflow.com/a
    # Posted by aborilov, modified by community. See post 'Timeline' for change history
    # Retrieved 2026-01-15, License - CC BY-SA 4.0
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - run: |
        cd js/tools && npm ci
    - name: Run script
      run: node js/tools/generate-sentences-report.js '${{ inputs.daysBackToGo }}' '${{ steps.extract_branch.outputs.branch }}'
