name: Report
on:
  workflow_dispatch:
    inputs:
        daysBackToGo:
          description: Days back to go
          required: false
          default: 1
          type: number
  workflow_call:
    inputs:
        site:
          description: site
          required: false
          default: 1
          type: number
jobs:
  report:
    runs-on: ubuntu-latest
    working-directory: 'js'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - uses: actions/setup-node@v6
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: |
        cd js && npm ci
    - name: Run script
      run: node tools/generate-sentences-report.js '${{ inputs.daysBackToGo }}'
