name: Unproven sites launcher
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  lawyersweekly_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: lawyersweekly.com.au
  eurekastreet_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: eurekastreet.com.au
  stockhouse_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stockhouse.com
  cjnews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cjnews.com
  kitco_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kitco.com
  thisismoney_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thisismoney.co.uk
  pressandjournal_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: pressandjournal.co.uk
  thecourier_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thecourier.co.uk
  sundaypost_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sundaypost.com
  marketoracle_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: marketoracle.co.uk
  biztechafrica_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: biztechafrica.com
  ghanasoccernet_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ghanasoccernet.com
  hk_asiatatler_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hk.asiatatler.com
  buddhistdoor_net:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: buddhistdoor.net
  irasia_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: irasia.com
  intellinews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: intellinews.com
  boatinternational_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: boatinternational.com
  bloombergquint_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bloombergquint.com
  businessinsider_in:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: businessinsider.in
  orissadiary_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: orissadiary.com
  gsmarena_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: gsmarena.com
  kbc_co_ke:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kbc.co.ke
  kdrtv_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kdrtv.com
  sundayobserver_lk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sundayobserver.lk
  dailynews_lk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: dailynews.lk
  themalaymailonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: themalaymailonline.com
  thesundaily_my:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thesundaily.my
  tribuneonlineng_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: tribuneonlineng.com
  techpoint_ng:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: techpoint.ng
  kemifilani_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kemifilani.com
  sundiatapost_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sundiatapost.com
  herald_ng:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: herald.ng
  thestreetjournal_org:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thestreetjournal.org
  nta_ng:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: nta.ng
  naij_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: naij.com
  m2woman_co_nz:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: m2woman.co.nz
  bworldonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bworldonline.com
  ph_asiatatler_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ph.asiatatler.com
  pageone_ph:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: pageone.ph
  philippinenews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: philippinenews.com
  oyeyeah_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: oyeyeah.com
  indonesiaexpat_biz:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: indonesiaexpat.biz
  sg_asiatatler_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sg.asiatatler.com
  hrdmag_com_sg:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hrdmag.com.sg
  networksasia_net:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: networksasia.net
  startribune_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: startribune.com
  neowin_net:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: neowin.net
  modernreaders_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: modernreaders.com

