name: Unproven sites launcher
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
jobs:
  brisbanetimes_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: brisbanetimes.com.au
  watoday_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: watoday.com.au
  illawarramercury_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: illawarramercury.com.au
  thecourier_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thecourier.com.au
  farmweekly_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: farmweekly.com.au
  bendigoadvertiser_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bendigoadvertiser.com.au
  westernadvocate_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: westernadvocate.com.au
  bordermail_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bordermail.com.au
  theland_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: theland.com.au
  examiner_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: examiner.com.au
  northerndailyleader_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: northerndailyleader.com.au
  theaureview_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: theaureview.com
  theadvocate_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: theadvocate.com.au
  stockandland_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stockandland.com.au
  adnews_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: adnews.com.au
  broadsheet_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: broadsheet.com.au
  sharecafe_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sharecafe.com.au
  investordaily_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: investordaily.com.au
  moneymanagement_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: moneymanagement.com.au
  noise11_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: noise11.com
  lawyersweekly_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: lawyersweekly.com.au
  eurekastreet_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: eurekastreet.com.au
  crn_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: crn.com.au
  greenandgoldrugby_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: greenandgoldrugby.com
  australasianlawyer_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: australasianlawyer.com.au
  traveller_com_au:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: traveller.com.au
  hcamag_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hcamag.com
  unb_com_bd:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: unb.com.bd
  bdnews24_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bdnews24.com
  tsn_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: tsn.ca
  windowscentral_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: windowscentral.com
  globalnews_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: globalnews.ca
  wellandtribune_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: wellandtribune.ca
  niagarafallsreview_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: niagarafallsreview.ca
  stockhouse_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stockhouse.com
  stcatharinesstandard_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stcatharinesstandard.ca
  kelownacapnews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kelownacapnews.com
  sootoday_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: sootoday.com
  fool_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: fool.ca
  mykawartha_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: mykawartha.com
  newswire_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: newswire.ca
  guelphtoday_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: guelphtoday.com
  cp24_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cp24.com
  stalbertgazette_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stalbertgazette.com
  barrietoday_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: barrietoday.com
  tbnewswatch_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: tbnewswatch.com
  medicinehatnews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: medicinehatnews.com
  orilliamatters_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: orilliamatters.com
  princegeorgecitizen_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: princegeorgecitizen.com
  paherald_sk_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: paherald.sk.ca
  ca_sports_yahoo_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ca.sports.yahoo.com
  thepeterboroughexaminer_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thepeterboroughexaminer.com
  baytoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: baytoday.ca
  pembinavalleyonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: pembinavalleyonline.com
  netnewsledger_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: netnewsledger.com
  technologynetworks_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: technologynetworks.com
  nsnews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: nsnews.com
  brandonsun_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: brandonsun.com
  prpeak_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: prpeak.com
  infotel_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: infotel.ca
  bradfordtoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bradfordtoday.ca
  panow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: panow.com
  citynews1130_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: citynews1130.com
  toronto_citynews_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: toronto.citynews.ca
  _660news_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 660news.com
  baystreet_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: baystreet.ca
  richmond-news_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: richmond-news.com
  timminstoday_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: timminstoday.com
  burnabynow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: burnabynow.com
  marketwired_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: marketwired.com
  bnn_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bnn.ca
  catholicregister_org:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: catholicregister.org
  ca_news_yahoo_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ca.news.yahoo.com
  innisfiltoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: innisfiltoday.ca
  cjnews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cjnews.com
  midlandtoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: midlandtoday.ca
  collingwoodtoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: collingwoodtoday.ca
  biv_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: biv.com
  ckom_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ckom.com
  energeticcity_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: energeticcity.ca
  chroniclejournal_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: chroniclejournal.com
  cjme_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cjme.com
  durhamregion_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: durhamregion.com
  insidehalton_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: insidehalton.com
  cfjctoday_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: cfjctoday.com
  nationalobserver_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: nationalobserver.com
  canadianlawyermag_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: canadianlawyermag.com
  bnnbloomberg_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bnnbloomberg.ca
  simcoe_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: simcoe.com
  hockeybuzz_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hockeybuzz.com
  _620ckrm_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 620ckrm.com
  rdnewsnow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: rdnewsnow.com
  advisor_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: advisor.ca
  kelownadailycourier_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kelownadailycourier.ca
  obj_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: obj.ca
  voiceonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: voiceonline.com
  exclaim_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: exclaim.ca
  myprincegeorgenow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: myprincegeorgenow.com
  mississauga_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: mississauga.com
  yorkregion_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: yorkregion.com
  nanaimonewsnow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: nanaimonewsnow.com
  whl_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: whl.ca
  kitco_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kitco.com
  straight_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: straight.com
  ctvnews_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ctvnews.ca
  canadianunderwriter_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: canadianunderwriter.ca
  _570news_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 570news.com
  theweathernetwork_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: theweathernetwork.com
  thesarniajournal_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thesarniajournal.ca
  niagarathisweek_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: niagarathisweek.com
  guelphmercury_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: guelphmercury.com
  trucknews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: trucknews.com
  thecjn_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thecjn.ca
  ckpgtoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ckpgtoday.ca
  queensjournal_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: queensjournal.ca
  lethbridgenewsnow_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: lethbridgenewsnow.com
  ca_finance_yahoo_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ca.finance.yahoo.com
  everythinggp_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: everythinggp.com
  halifaxtoday_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: halifaxtoday.ca
  ubyssey_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ubyssey.ca
  themarketherald_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: themarketherald.ca
  canadianinquirer_net:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: canadianinquirer.net
  thecoast_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thecoast.ca
  northernontariobusiness_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: northernontariobusiness.com
  hilltimes_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hilltimes.com
  benefitscanada_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: benefitscanada.com
  timescolonist_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: timescolonist.com
  thelinknewspaper_ca:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thelinknewspaper.ca

