name: Unproven sites launcher 0
on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'
jobs:
  stockhouse_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: stockhouse.com
  thecourier_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: thecourier.co.uk
  intellinews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: intellinews.com
  boatinternational_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: boatinternational.com
