name: Unproven sites launcher 3
on:
  workflow_dispatch:
jobs:
  MyBangalore:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MyBangalore
  Gaadi_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Gaadi.com
  HardNews_Magazine:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: HardNews Magazine
  Sciblog:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Sciblog
  ProPakistani_p:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ProPakistani.p
  H88_com_sg:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: H88.com.sg
  Film_Business_Asia:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Film Business Asia
  NewsMax_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: NewsMax.com
  al_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: al.co
  AnnArbor_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AnnArbor.com
  PRLog_Or:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: PRLog.Or
  MindShift:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MindShift
  BuddyTV:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: BuddyTV
  AllGov:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AllGov
  Syracuse_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Syracuse.co
  Artistdirect_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Artistdirect.com
  Shadowlocke:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Shadowlocke
  Geeks_of_Doom:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Geeks of Doom
  Becker_s_ASC_Review:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Becker's ASC Review
  Minyanville_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Minyanville.com
  Zap2it_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Zap2it.co
  Southern_Fried_Science:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Southern Fried Science
  Hotel_News_Now:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Hotel News Now
  hcp_obgyn_net:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: hcp.obgyn.net
  Bundaberg_NewsMail:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Bundaberg NewsMail
  The_Gympie_Times:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: The Gympie Times
  Coff_s_Coast_Advocate:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Coff's Coast Advocate
  Western_Standar:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Western Standar
  Moneysupermarket_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Moneysupermarket.com
  GoFishing_UK:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: GoFishing UK
  eFestivals_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: eFestivals.co.uk
  Greenwise_Business:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Greenwise Business
  FootballFanCast_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FootballFanCast.co
  ElectricPig_co_uk:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: ElectricPig.co.uk
  Ghana_News:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Ghana News
  India_Forums_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: India-Forums.com
  MediaNama_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: MediaNama.co
  TechGadgets_i:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: TechGadgets.i
  _1888_Press_Releas:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: 1888 Press Releas
  Veterans_Today_Network:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Veterans Today Network
  Beliefnet_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Beliefnet.co
  Salem_News_Com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Salem-News.Com
  Collider_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Collider.co
  PerezHilton_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: PerezHilton.co
  Kotaku_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Kotaku.co
  Search_Engine_Lan:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Search Engine Lan
  OregonLive_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: OregonLive.co
  AdAge_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AdAge.co
  SanFranciscoSentinel_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: SanFranciscoSentinel.com
  Payvand:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Payvand
  CNNMoney_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: CNNMoney.com
  Natural_News_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Natural News.com
  Prison_Planet_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: Prison Planet.com
  AmmoLand_co:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: AmmoLand.co
  FindLaw:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: FindLaw
