name: Unproven sites launcher 1
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
jobs:
  gsmarena_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: gsmarena.com
  kbc_co_ke:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kbc.co.ke
  kdrtv_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kdrtv.com
  kemifilani_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: kemifilani.com
  naij_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: naij.com
  bworldonline_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: bworldonline.com
  philippinenews_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: philippinenews.com
  startribune_com:
    uses: wordnik/nyt-first-said/.github/workflows/brush.yml@master
    secrets: inherit
    with:
      site: startribune.com
